"""update_user_model_remove_password_add_uid

Revision ID: 57316acce5fe
Revises: 344f2735de14
Create Date: 2025-07-09 13:03:05.937842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57316acce5fe'
down_revision: Union[str, None] = '344f2735de14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
