"""remove_username_from_user_model

Revision ID: 5acd8739f2fa
Revises: 57316acce5fe
Create Date: 2025-07-09 14:10:05.585199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acd8739f2fa'
down_revision: Union[str, None] = '57316acce5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###
