"""add created_at to category model

Revision ID: e4f2dfaec936
Revises: 5acd8739f2fa
Create Date: 2025-07-09 14:17:35.227289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f2dfaec936'
down_revision: Union[str, None] = '5acd8739f2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
