"""characteristic

Revision ID: 98495cdda829
Revises: 74e3bbe00b95
Create Date: 2025-06-20 17:22:01.045495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98495cdda829'
down_revision = '74e3bbe00b95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 