"""add_description_to_vendor_profile

Revision ID: 48a1db15a68b
Revises: e9a9b3f3b6e7
Create Date: 2025-06-25 15:16:34.393769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48a1db15a68b'
down_revision = 'e9a9b3f3b6e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_profiles', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_profiles', 'description')
    # ### end Alembic commands ### 