"""Change product status default to approved

Revision ID: 47814649863c
Revises: 98495cdda829
Create Date: 2025-06-23 12:57:52.765836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47814649863c'
down_revision = '98495cdda829'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 