"""Add favorite

Revision ID: 207c82e71fc3
Revises: cc4cb85d03e2
Create Date: 2025-06-24 12:48:22.619319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207c82e71fc3'
down_revision = 'cc4cb85d03e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 