"""Add vendor_profile_id to products table

Revision ID: e9a9b3f3b6e7
Revises: 207c82e71fc3
Create Date: 2025-06-24 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a9b3f3b6e7'
down_revision = '207c82e71fc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vendor_profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        'fk_products_vendor_profile_id_vendor_profiles',
        'products', 'vendor_profiles',
        ['vendor_profile_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_vendor_profile_id_vendor_profiles', 'products', type_='foreignkey')
    op.drop_column('products', 'vendor_profile_id')
    # ### end Alembic commands ### 