services:
  app:
    build: .
    container_name: denas_fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DB_ENV=${DB_ENV:-supabase}
    env_file:
      - env/.env.supabase
    volumes:
      - .:/code
